# Generated by Django 4.0.3 on 2022-04-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msjs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
