# Generated by Django 4.0.3 on 2022-05-03 04:19

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msjs', '0002_message_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default="POINT(1,1)", srid=4326),
        ),
        migrations.CreateModel(
            name='MessageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='msjs.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Like',
                'verbose_name_plural': 'Message Likes',
            },
        ),
    ]
