# Generated by Django 4.0.3 on 2022-05-03 04:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msjs', '0003_alter_message_location_messagelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(1,1)', srid=4326),
        ),
    ]
